/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Already played before? Load your savefile": "以前玩过吗？ 加载你的保存文件",
    "Close all": "关闭所有",
    "Dark mode": "深色模式",
    "Deutsch": "德语",
    "English": "中文",
    "Gooboo": "Gooboo",
    "here": "这里",
    "Language": "语言",
    "New game": "新游戏",
    "s": "s",
    "Automation": "自动化",
    "Autosave": "自动保存",
    "Autosave hint": "自动保存提示",
    "Average": "平均",
    "Backup hint": "备份提示",
    "Base value": "基础值",
    "Based on the sum of multiple values. Used to unlock new features": "基于多个值的总和。 用于解锁新功能",
    "Bottom right": "右下角",
    "Check for updates": "检查更新",
    "Confirmation": "确认",
    "Damage": "伤害",
    "Durability": "耐用性",
    "Export to file": "导出到文件",
    "Features": "功能",
    "Gain": "增益",
    "Gain scrap each time you deal damage after you destroyed this rock at least once. When you destroy a rock you gain 5x scrap rewards": "在你摧毁这块岩石至少一次后，每次造成伤害都会获得碎片。 当您摧毁一块岩石时，您将获得 5 倍废料奖励",
    "Game saved": "游戏已保存",
    "Generic": "通用",
    "Global level": "全局等级",
    "Icon and text": "图标和文字",
    "Keybinds": "按键绑定",
    "Load from file": "从文件加载",
    "Mine": "矿山",
    "Mining": "采矿",
    "Mining autoprogress limit": "挖矿自动进度限制",
    "Mining: Deepest ore mine rock broken": "采矿：最深矿井岩石击破",
    "Next main feature": "下一个主要特点",
    "Note hint": "注意提示",
    "Notes": "笔记",
    "Notifications": "通知",
    "Pause": "暂停",
    "Performance": "性能",
    "Position": "位置",
    "Prestiges": "声望",
    "Read": "阅读",
    "Relative upgrade stats": "相对升级统计",
    "Scrap": "废料",
    "Shows the difference instead of before / after values": "显示差异而不是之前/之后的值",
    "Smooth": "光滑的",
    "Tab display": "选项卡显示",
    "Text shadows": "文字阴影",
    "The amount of damage needed to break this rock": "击破这块岩石所需的伤害量",
    "Time needed to break the current rock": "击破目前的石头需要时间",
    "Upgrades": "升级",
    "Upgrades per page": "每页升级数",
    "Use pickaxe. Dig deeper.": "使用镐。 深入挖掘。",
    "When breaking a rock for the first time, you automatically advance to the next depth if breaking it takes X seconds or less": "第一次击碎岩石时，如果击碎需要 X 秒或更短时间，您会自动前进到下一个深度",
    "You do not gain scrap yet because this rock has never been broken": "你还没有获得废料，因为这块岩石从未被击碎过",
    "Buy": "购买",
    "Capacity": "容量",
    "Collect scrap. Buy upgrades.": "收集废料。 购买升级。",
    "Damage +": "伤害+",
    "Damage:": "伤害：",
    "For some reason, the underground rocks are full of scrap! But this can also be a good thing, scrap is versatile and can be used to create almost anything": "不知道为什么，地下岩石里充满了废料！ 但这也可能是一件好事，废料用途广泛，几乎可以用来创造任何东西",
    "Max": "最大",
    "Can't afford": "买不起",
    "Reach new depths. Reveal new upgrades.": "达到新的深度。 揭示新的升级。",
    "You do not get scrap when hitting rocks you have never broken before. Sometimes it is smarter to stay on your current depth to collect more scrap instead of digging down immediately.": "当撞击您以前从未击碎过的岩石时，您不会产生废料。 有时，留在当前深度收集更多废料比立即向下挖掘更明智。",
    "Increase global level. Unlock new features. See requirement in feature list.": "提高全局等级。 解锁新功能。 请参阅功能列表中的要求。",
    "Check settings. Descending can be automated.": "检查设置。 可以自动化向下挖掘。",
    "This game is free and has no microtransactions or ads. If you want to support the development, check out my patreon page:": "该游戏是免费的，没有微交易或广告。 如果您想支持开发，请查看我的 patreon 页面：",
    "Time units": "时间单位",
    "View patch notes": "查看补丁说明",
    "View source code": "查看源码",
    "Used technologies": "使用的技术",
    "To keep numbers readable, extremely big (and small) numbers are formatted using the units below.": "为了保持数字的可读性，极大（和极小）的数字使用以下单位进行格式化。",
    "Support me": "支持作者",
    "Small numbers": "小数字",
    "Automated testing:": "自动化测试：",
    "Big numbers": "大数字",
    "developed by Tendsty": "开发者：Tendsty",
    "Gooboo can be played on its own without the need for external guides. But if you feel like hanging out with other players, you can visit these places:": "Gooboo 可以单独玩，无需外部指南。 但如果您想与其他玩家一起出去玩，您可以访问以下地方：",
    "Gooboo is an idle / incremental game where you manage multiple features in a mysterious, unknown world. Gather different resources to buy a huge variety of upgrades to increase your resource gains. Progress in your main features to unlock new content and learn more about this world. And when progression starts slowing down, prestige individual features to take your gains to the next level.": "Gooboo 是一款放置/增量游戏，您可以在神秘、未知的世界中管理多个功能。 收集不同的资源来购买各种各样的升级，以增加你的资源收益。 取得主要功能的进展以解锁新内容并了解有关这个世界的更多信息。 当进度开始放缓时，声望个人功能可以将您的收获提升到一个新的等级。",
    "Hour": "小时",
    "Minute": "分钟",
    "Number formatting": "数字格式",
    "You are using the web version. The game regularly checks for updates, automatically uses the newest version and notifies you when an update is available.": "您使用的是网页版。 游戏会定期检查更新，自动使用最新版本，并在有可用更新时通知您。",
    "Socials": "社交",
    "Second": "秒",
    "Day": "天",
    "Upgrades bought": "已购买升级",
    "Scrap gain +": "废料增益 +",
    "Scrap gain:": "废料增益：",
    "Expand resource capacity. Buy bigger upgrades. Avoid resource waste.": "扩大资源容量。 购买更大的升级。 避免资源浪费。",
    "Feature": "功能",
    "Gain new gems every time the bar fills. The generator creates new gems every 1h 00m.": "每次进度条填满时都会获得新的宝石。 生成器每 1 小时 0 分钟创建新宝石。",
    "Gems": "宝石",
    "Generate gems. Takes time. Buy premium upgrades.": "生成宝石。 需要时间。 购买高级升级。",
    "More damage": "更多伤害",
    "More scrap": "更多废料",
    "New feature unlocked!": "新功能已解锁！",
    "Reduces incoming damage by a flat amount": "将受到的伤害减少固定数量",
    "Scrap capacity:": "废料容量：",
    "Toughness": "韧性",
    "Leave whenever you want. Everything here keeps working.": "你想什么时候离开就什么时候离开。 这里的一切都在继续运转。",
    "Capacity too low": "容量太低",
    "Collector": "收集者",
    "Grass, small plants, leaves, doesn't matter. They are all useful": "草，小植物，树叶，都没关系。 它们都很有用",
    "Logs harvested from nearby trees": "从附近树木采伐的原木",
    "Lonely creature. Send it to collect.": "孤独的居民。 派出收集资源。",
    "Material": "材料",
    "Plant fiber": "植物纤维",
    "Plant fiber gain:": "植物纤维增益：",
    "Scrap capacity +": "废料容量+",
    "Small rocks your creatures collected": "你的居民收集的小石头",
    "Stone": "石头",
    "Stone gain:": "石增益：",
    "Unemployed": "失业者",
    "Unemployed citizens do not produce resources. Assign them to a job below": "失业的人口不生产资源。 将他们分配给以下工作",
    "Village": "村庄",
    "Wood": "木头",
    "Wood gain:": "木材增益：",
    "Income is reduced to 25% due to overcap": "收入因上限减少至 25%",
    "Multiple features. All keep working at the same time.": "多种功能。 所有人同时继续工作。",
    "Building speed:": "建造速度：",
    "Plant fiber capacity:": "植物纤维容量：",
    "Overtime": "随着时间的推移",
    "Faster building": "更快的建造",
    "Fonts:": "字体:",
    "Gold coin gain:": "金币增益：",
    "Golden throne": "黄金王座",
    "Material gain:": "材料增益：",
    "More plant fiber": "更多植物纤维",
    "Extract ore. Buy more upgrades.": "提取矿石。 购买更多升级。",
    "Aluminium ore": "铝矿石",
    "Can be found at 15m or below": "可以在15米以下找到",
    "You do not gain ore yet because this rock has never been broken": "您还没有获得矿石，因为这块岩石从未被击碎过",
    "Aluminium ore gain:": "铝矿石增益：",
    "Aluminium ore capacity:": "铝矿石容量：",
    "More aluminium": "更多铝",
    "Toughness is severely reducing your damage": "韧性正在大幅减少你的伤害",
    "Aluminium cache": "铝存储",
    "Aluminium hardening": "铝淬火",
    "Reach goals. Get achievements. Generate gems faster.": "达到目标。 获得成就。 更快地生成宝石。",
    "Deeprun": "深渊",
    "Destruction": "毁灭",
    "Diversity": "多元化",
    "Game": "游戏",
    "Highest wood, plant fiber or stone amount": "最高的木材、植物纤维或石材含量",
    "Knock on wood": "敲木头",
    "Maximum depth": "最大深度",
    "Maximum depth in under 15 minutes": "15 分钟内达到最大深度",
    "More ore": "更多矿石",
    "Most damage in one hit": "一击造成最大伤害",
    "Ore gained": "获得矿石",
    "Ore types found": "发现的矿石类型",
    "Power": "力量",
    "Scrap gained": "获得废钢",
    "Scrapheap": "垃圾堆",
    "This is deep": "这很深",
    "Total damage dealt": "造成的总伤害",
    "More wood": "更多木头",
    "Toughness is too high to deal any damage": "韧性太高，无法造成任何伤害",
    "Wood capacity:": "木头容量：",
    "Finally, something that is not scrap. In its unrefined form its use is limited, but that does not mean useless": "最后，有些东西不是废料。 在其未完善的形式中，它的用途是有限的，但这并不意味着无用",
    "More stone": "更多石头",
    "Stone capacity:": "石头容量",
    "A dark blue gem that can be used to buy consumables to help you progress faster": "深蓝色宝石，可用于购买消耗品，帮助你更快进步",
    "A dull green gem that can be used to buy various improvements. Your villagers seem to like it": "暗绿色宝石，可用于购买各种改进品。 你们的村民似乎很喜欢它",
    "A shiny red gem that can be exchanged for powerful permanent upgrades": "闪亮的红色宝石，可以兑换强大的永久升级",
    "Amethyst": "紫水晶",
    "Emerald": "翡翠",
    "Ruby": "红宝石",
    "Sapphire": "蓝宝石",
    "This beautiful purple gem can be used to buy themes or other cosmetic items": "这种美丽的紫色宝石可用于购买主题或其他化妆品",
    "Dig deeper. Find more ore.": "挖得更深一些。 寻找更多矿石。",
    "Excavator": "挖掘机",
    "Achievement get!": "获得成就！",
    "Overachiever": "功成名就",
    "This relic is given as a reward when completing the next level of this achievement.": "当完成该成就的下一等级时，将给予该遗物作为奖励。",
    "Total level of other achievements": "其他成就总等级",
    "Build": "建造",
    "Build hut. Attract more creatures.": "建造小屋。 吸引更多的居民。",
    "Building speed": "建造速度",
    "Buildings constructed": "已建成的建筑物",
    "Campfire": "营火",
    "Community center": "社区中心",
    "Farm": "农场",
    "Farmer": "农民",
    "Farmer:": "农民：",
    "Grain gain:": "谷物增益：",
    "Harvester:": "收割机：",
    "Hut": "小屋",
    "Miner:": "矿工：",
    "No upgrades found": "未发现升级",
    "Peaceful farm. Crops grow. Produce food.": "宁静的农场。 庄稼生长。 生产食物。",
    "Plantation": "种植园",
    "Queue empty": "队列为空",
    "This building counts as a workstation": "这座建筑算作一个工作站",
    "Total buildings constructed": "已建成建筑物总数",
    "Total housing constructed (first 25 per building)": "已建成住房总数（每栋建筑前 25 栋）",
    "Unlock: Tier 1 buildings": "解锁：1 级建筑",
    "Unlock: Tier 2 buildings": "解锁：2级建筑",
    "Village: Maximum housing": "村庄：最大住房数量",
    "Workers:": "工人：",
    "Fruit trees. Also produce food.": "果树。 还生产粮食。",
    "Do not neglect features. All important.": "不要忽视功能。 都很重要。",
    "Creatures look weird. Brown and hairy.": "居民看起来很奇怪。 棕色且多毛。",
    "Take an exam, where you have 1m 15s to get the highest possible score. You will receive golden dust as reward (150 - 199, based on your performance and chosen grade). If you achieve a score of 12, the exam is rated as perfect and you unlock the next grade.": "参加考试，您有 1 分 15 秒的时间来获得尽可能高的分数。 您将收到金粉作为奖励（150 - 199，根据您的表现和所选等级）。 如果您获得 12 分，则考试被评为完美，您可以解锁下一个等级。",
    " Study a bit first!": "先学一点吧！",
    "Ancient hourglass": "古老的沙漏",
    "Be patient. Think about purchases. Gems take long to get.": "要有耐心。 考虑购买。 宝石需要很长时间才能获得。",
    "Book": "书本",
    "Cancel": "取消",
    "Convert": "转换",
    "Convert exam passes to golden dust": "将考试合格证转化为金粉",
    "Each unlocked subject gives 10 books per hour, no matter the grade.": "每个解锁科目每小时提供 10 本书，无论年级如何。",
    "Exam pass": "考试通过",
    "Get new books. Every hour. Even more with better grades.": "获取新书。 每隔一小时。 成绩更好的话甚至更多。",
    "Get the highest possible score in 40s, and get a chance to improve your grade if you study on your best grade. Depending on your score, you gain (or lose) progress to the next grade. An average score of 6 is expected.": "在40秒内获得尽可能高的分数，如果你以最好的成绩学习，就有机会提高你的成绩。 根据您的分数，您会获得（或失去）升入下一年级的进度。 预计平均分为 6 分。",
    "Golden dust": "金尘",
    "Grades": "成绩",
    "Grades determine the difficulty of this subject. You can switch between grades at any time and unlock better grades by studying enough or getting a perfect exam score.": "成绩决定了该科目的难度。 您可以随时切换成绩，通过足够的学习或获得完美的考试成绩来解锁更好的成绩。",
    "It's hard to carry these heavy books": "搬运这些重书很困难",
    "Learn in school. Answer correctly. Get good grades.": "在学校学习。 正确回答。 取得好成绩。",
    "Math": "数学",
    "Practice": "实践",
    "Practice this subject without time pressure, but gain no rewards or grades": "在没有时间压力的情况下练习该科目，但不会获得任何奖励或成绩",
    "Requires ": "需要",
    "School": "学校",
    "Skip": "跳过",
    "Skip time for this feature": "跳过此功能的时间",
    "Solve equations": "求解方程式",
    "Still learning": "还在学习中",
    "Strange, we didn't need them at our old school. Here they are needed to take an exam": "奇怪的是，我们原来的学校不需要它们。 这里需要他们参加考试",
    "Study": "学习",
    "Take exam": "参加考试",
    "Time (in minutes)": "时间（分钟）",
    "You are new to this school, reducing your golden dust reward to 25%. Reach a higher global level to reduce this penalty, and remove it entirely by reaching global level 175.": "你是这所学校的新手，你的金尘奖励减少到25%。 达到更高的全局等级可以减少此惩罚，并通过达到全局等级 175 来完全消除它。",
    "You cannot lose grade progress at F grade.": "您不能失去 F 级的成绩进度。",
    "You cannot take exams at F grade.": "您不能参加 F 级考试。",
    "Food": "食物",
    "Fruit": "水果",
    "Fruit gain:": "果实增益：",
    "Grain": "粮食",
    "Grain from plants grown in the village. You think this should be processed before eating it, but the villagers don't care": "村里种植的植物的谷物。 你认为这个应该加工一下再吃，但村民不在乎",
    "Harvester": "收割机",
    "Sweet and juicy fruit, the villagers love these": "果实香甜多汁，深受村民喜爱",
    "Book gain:": "书本增益：",
    "Student": "学生",
    "Achievement hint": "成就提示",
    "Bottom": "底部",
    "Bottom left": "左下",
    "Common": "常见",
    "Dark mine is scary. But give metal.": "黑暗的我是可怕的。 但是给金属。",
    "Gem purchases": "宝石购买",
    "Icon only": "仅图标",
    "Increased": "增加",
    "Off": "关闭",
    "Particle amount": "粒子量",
    "Rare": "稀有",
    "Reduced": "降低",
    "Simple": "简单",
    "Text only": "仅文本",
    "Top": "顶部",
    "Top left": "左上",
    "Top right": "右上",
    "Metal": "金属",
    "Metal gain:": "金属增益：",
    "Miner": "矿工",
    "Your creatures found this metal by digging underground. Seems like the ground beneath this village isn't full of scrap": "你的生物通过挖掘地下发现了这种金属。 看来这个村庄的地下并没有充满废料",
    "Buy crafting station. Make better pickaxes.": "购买制作站。 制作更好的镐。",
    "Crafting station": "制作站",
    "Global level. Need to unlock new features. Progress in features to increase.": "全球水平。 需要解锁新功能。 进步功能增加。",
    "The crafting station allows you to consume ores to raise your pickaxe power and is essential to increase your damage": "制作站可以让你消耗矿石来提高你的镐的力量，这对于增加你的伤害至关重要",
    "Unlock: Pickaxe crafting": "解锁：制作镐子",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Save (": "保存 (",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "/s": "/秒",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.]+)K$/,
    /^([\d\.]+)K \/ ([\d\.]+)K$/,
    /^([\d\.]+)M \/ ([\d\.]+)M$/,
    /^([\d\.]+)K \/ ([\d\.]+)M$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^This rock was broken (.+) time$/, '距离这块岩石被击破还需要 $1 次'],
    [/^This rock was broken (.+) times$/, '距离这块岩石被击破还需要 $1 次'],
    [/^Gain (.+) on hit, (.+) on break, (.+) per second$/, '击中时获得 $1，击碎时获得 $2 ，每秒 $3'],
    [/^Next upgrade unlocks at (.+) Maximum depth$/, '下一次升级将在最大深度 $1 处解锁'],
    [/^Gain new gems every time the bar fills. Each achievement increases generation speed by (.+). Your (.+) achievements increase generation speed by (.+), from (.+) to (.+).$/, '每次进度条填满时都会获得新的宝石。 每项成就都会使生成速度提高 $1。 你的 $2 成就将生成速度提高 $3，从 $4 到 $5。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^You get a new exam pass every day \(next one in (.+)\) and every (.+) global levels.$/, '您每天都会获得一张新的考试通行证（下一张在 $1 内），并且每 $2 个全局等级都会获得一张新的考试通行证。'],
    [/^Consuming up to (.+) per second$/, '每秒最多消耗 $1'],
    [/^Note (.+) found$/, '发现笔记 $1'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+)m$/, '$1米'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);