/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Already played before? Load your savefile": "以前玩过吗？ 加载你的保存文件",
    "Close all": "关闭所有",
    "Dark mode": "深色模式",
    "Deutsch": "德语",
    "English": "中文",
    "Gooboo": "Gooboo",
    "here": "这里",
    "Language": "语言",
    "New game": "新游戏",
    "s": "s",
    "Automation": "自动化",
    "Autosave": "自动保存",
    "Autosave hint": "自动保存提示",
    "Average": "平均",
    "Backup hint": "备份提示",
    "Base value": "基础值",
    "Based on the sum of multiple values. Used to unlock new features": "基于多个值的总和。 用于解锁新功能",
    "Bottom right": "右下角",
    "Check for updates": "检查更新",
    "Confirmation": "确认",
    "Damage": "伤害",
    "Durability": "耐用性",
    "Export to file": "导出到文件",
    "Features": "功能",
    "Gain": "增益",
    "Gain scrap each time you deal damage after you destroyed this rock at least once. When you destroy a rock you gain 5x scrap rewards": "在你摧毁这块岩石至少一次后，每次造成伤害都会获得碎片。 当您摧毁一块岩石时，您将获得 5 倍废料奖励",
    "Game saved": "游戏已保存",
    "Generic": "通用",
    "Global level": "全局等级",
    "Icon and text": "图标和文字",
    "Keybinds": "按键绑定",
    "Load from file": "从文件加载",
    "Mine": "矿山",
    "Mining": "采矿",
    "Mining autoprogress limit": "挖矿自动进度限制",
    "Mining: Deepest ore mine rock broken": "采矿：最深矿井岩石击破",
    "Next main feature": "下一个主要功能",
    "Note hint": "注意提示",
    "Notes": "笔记",
    "Notifications": "通知",
    "Pause": "暂停",
    "Performance": "性能",
    "Position": "位置",
    "Prestiges": "声望",
    "Read": "阅读",
    "Relative upgrade stats": "相对升级统计",
    "Scrap": "废料",
    "Shows the difference instead of before / after values": "显示差异而不是之前/之后的值",
    "Smooth": "光滑的",
    "Tab display": "选项卡显示",
    "Text shadows": "文字阴影",
    "The amount of damage needed to break this rock": "击破这块岩石所需的伤害量",
    "Time needed to break the current rock": "击破目前的石头需要时间",
    "Upgrades": "升级",
    "Upgrades per page": "每页升级数",
    "Use pickaxe. Dig deeper.": "使用镐。 深入挖掘。",
    "When breaking a rock for the first time, you automatically advance to the next depth if breaking it takes X seconds or less": "第一次击碎岩石时，如果击碎需要 X 秒或更短时间，您会自动前进到下一个深度",
    "You do not gain scrap yet because this rock has never been broken": "你还没有获得废料，因为这块岩石从未被击碎过",
    "Buy": "购买",
    "Capacity": "容量",
    "Collect scrap. Buy upgrades.": "收集废料。 购买升级。",
    "Damage +": "伤害+",
    "Damage:": "伤害：",
    "For some reason, the underground rocks are full of scrap! But this can also be a good thing, scrap is versatile and can be used to create almost anything": "不知道为什么，地下岩石里充满了废料！ 但这也可能是一件好事，废料用途广泛，几乎可以用来创造任何东西",
    "Max": "最大",
    "Can't afford": "买不起",
    "Reach new depths. Reveal new upgrades.": "达到新的深度。 揭示新的升级。",
    "You do not get scrap when hitting rocks you have never broken before. Sometimes it is smarter to stay on your current depth to collect more scrap instead of digging down immediately.": "当撞击您以前从未击碎过的岩石时，您不会产生废料。 有时，留在当前深度收集更多废料比立即向下挖掘更明智。",
    "Increase global level. Unlock new features. See requirement in feature list.": "提高全局等级。 解锁新功能。 请参阅功能列表中的要求。",
    "Check settings. Descending can be automated.": "检查设置。 可以自动化向下挖掘。",
    "This game is free and has no microtransactions or ads. If you want to support the development, check out my patreon page:": "该游戏是免费的，没有微交易或广告。 如果您想支持开发，请查看我的 patreon 页面：",
    "Time units": "时间单位",
    "View patch notes": "查看补丁说明",
    "View source code": "查看源码",
    "Used technologies": "使用的技术",
    "To keep numbers readable, extremely big (and small) numbers are formatted using the units below.": "为了保持数字的可读性，极大（和极小）的数字使用以下单位进行格式化。",
    "Support me": "支持作者",
    "Small numbers": "小数字",
    "Automated testing:": "自动化测试：",
    "Big numbers": "大数字",
    "developed by Tendsty": "开发者：Tendsty",
    "Gooboo can be played on its own without the need for external guides. But if you feel like hanging out with other players, you can visit these places:": "Gooboo 可以单独玩，无需外部指南。 但如果您想与其他玩家一起出去玩，您可以访问以下地方：",
    "Gooboo is an idle / incremental game where you manage multiple features in a mysterious, unknown world. Gather different resources to buy a huge variety of upgrades to increase your resource gains. Progress in your main features to unlock new content and learn more about this world. And when progression starts slowing down, prestige individual features to take your gains to the next level.": "Gooboo 是一款放置/增量游戏，您可以在神秘、未知的世界中管理多个功能。 收集不同的资源来购买各种各样的升级，以增加你的资源收益。 取得主要功能的进展以解锁新内容并了解有关这个世界的更多信息。 当进度开始放缓时，声望个人功能可以将您的收获提升到一个新的等级。",
    "Hour": "小时",
    "Minute": "分钟",
    "Number formatting": "数字格式",
    "You are using the web version. The game regularly checks for updates, automatically uses the newest version and notifies you when an update is available.": "您使用的是网页版。 游戏会定期检查更新，自动使用最新版本，并在有可用更新时通知您。",
    "Socials": "社交",
    "Second": "秒",
    "Day": "天",
    "Upgrades bought": "已购买升级",
    "Scrap gain +": "废料增益 +",
    "Scrap gain:": "废料增益：",
    "Expand resource capacity. Buy bigger upgrades. Avoid resource waste.": "扩大资源容量。 购买更大的升级。 避免资源浪费。",
    "Feature": "功能",
    "Gain new gems every time the bar fills. The generator creates new gems every 1h 00m.": "每次进度条填满时都会获得新的宝石。 生成器每 1 小时 0 分钟创建新宝石。",
    "Gems": "宝石",
    "Generate gems. Takes time. Buy premium upgrades.": "生成宝石。 需要时间。 购买高级升级。",
    "More damage": "更多伤害",
    "More scrap": "更多废料",
    "New feature unlocked!": "新功能已解锁！",
    "Reduces incoming damage by a flat amount": "将受到的伤害减少固定数量",
    "Scrap capacity:": "废料容量：",
    "Toughness": "韧性",
    "Leave whenever you want. Everything here keeps working.": "你想什么时候离开就什么时候离开。 这里的一切都在继续运转。",
    "Capacity too low": "容量太低",
    "Collector": "收集者",
    "Grass, small plants, leaves, doesn't matter. They are all useful": "草，小植物，树叶，都没关系。 它们都很有用",
    "Logs harvested from nearby trees": "从附近树木采伐的原木",
    "Lonely creature. Send it to collect.": "孤独的居民。 派出收集资源。",
    "Material": "材料",
    "Plant fiber": "植物纤维",
    "Plant fiber gain:": "植物纤维增益：",
    "Scrap capacity +": "废料容量+",
    "Small rocks your creatures collected": "你的居民收集的小石头",
    "Stone": "石头",
    "Stone gain:": "石增益：",
    "Unemployed": "失业者",
    "Unemployed citizens do not produce resources. Assign them to a job below": "失业的人口不生产资源。 将他们分配给以下工作",
    "Village": "村庄",
    "Wood": "木头",
    "Wood gain:": "木材增益：",
    "Income is reduced to 25% due to overcap": "收入因上限减少至 25%",
    "Multiple features. All keep working at the same time.": "多种功能。 所有人同时继续工作。",
    "Building speed:": "建造速度：",
    "Plant fiber capacity:": "植物纤维容量：",
    "Overtime": "随着时间的推移",
    "Faster building": "更快的建造",
    "Fonts:": "字体:",
    "Gold coin gain:": "金币增益：",
    "Golden throne": "黄金王座",
    "Material gain:": "材料增益：",
    "More plant fiber": "更多植物纤维",
    "Extract ore. Buy more upgrades.": "提取矿石。 购买更多升级。",
    "Aluminium ore": "铝矿石",
    "You do not gain ore yet because this rock has never been broken": "您还没有获得矿石，因为这块岩石从未被击碎过",
    "Aluminium ore gain:": "铝矿石增益：",
    "Aluminium ore capacity:": "铝矿石容量：",
    "More aluminium": "更多铝",
    "Toughness is severely reducing your damage": "韧性正在大幅减少你的伤害",
    "Aluminium cache": "铝存储",
    "Aluminium hardening": "铝淬火",
    "Reach goals. Get achievements. Generate gems faster.": "达到目标。 获得成就。 更快地生成宝石。",
    "Deeprun": "深渊",
    "Destruction": "毁灭",
    "Diversity": "多元化",
    "Game": "游戏",
    "Highest wood, plant fiber or stone amount": "最高的木材、植物纤维或石材含量",
    "Knock on wood": "敲木头",
    "Maximum depth": "最大深度",
    "Maximum depth in under 15 minutes": "15 分钟内达到最大深度",
    "More ore": "更多矿石",
    "Most damage in one hit": "一击造成最大伤害",
    "Ore gained": "获得矿石",
    "Ore types found": "发现的矿石类型",
    "Power": "能量",
    "Scrap gained": "获得废钢",
    "Scrapheap": "垃圾堆",
    "This is deep": "这很深",
    "Total damage dealt": "造成的总伤害",
    "More wood": "更多木头",
    "Toughness is too high to deal any damage": "韧性太高，无法造成任何伤害",
    "Wood capacity:": "木头容量：",
    "Finally, something that is not scrap. In its unrefined form its use is limited, but that does not mean useless": "最后，有些东西不是废料。 在其未完善的形式中，它的用途是有限的，但这并不意味着无用",
    "More stone": "更多石头",
    "Stone capacity:": "石头容量",
    "A dark blue gem that can be used to buy consumables to help you progress faster": "深蓝色宝石，可用于购买消耗品，帮助你更快进步",
    "A dull green gem that can be used to buy various improvements. Your villagers seem to like it": "暗绿色宝石，可用于购买各种改进品。 你们的村民似乎很喜欢它",
    "A shiny red gem that can be exchanged for powerful permanent upgrades": "闪亮的红色宝石，可以兑换强大的永久升级",
    "Amethyst": "紫水晶",
    "Emerald": "翡翠",
    "Ruby": "红宝石",
    "Sapphire": "蓝宝石",
    "This beautiful purple gem can be used to buy themes or other cosmetic items": "这种美丽的紫色宝石可用于购买主题或其他化妆品",
    "Dig deeper. Find more ore.": "挖得更深一些。 寻找更多矿石。",
    "Excavator": "挖掘机",
    "Achievement get!": "获得成就！",
    "Overachiever": "功成名就",
    "This relic is given as a reward when completing the next level of this achievement.": "当完成该成就的下一等级时，将给予该遗物作为奖励。",
    "Total level of other achievements": "其他成就总等级",
    "Build": "建造",
    "Build hut. Attract more creatures.": "建造棚屋。 吸引更多的居民。",
    "Building speed": "建造速度",
    "Buildings constructed": "已建成的建筑物",
    "Campfire": "营火",
    "Community center": "社区中心",
    "Farm": "农场",
    "Farmer": "农民",
    "Farmer:": "农民：",
    "Grain gain:": "谷物增益：",
    "Harvester:": "收割机：",
    "Hut": "棚屋",
    "Miner:": "矿工：",
    "No upgrades found": "未发现升级",
    "Peaceful farm. Crops grow. Produce food.": "宁静的农场。 庄稼生长。 生产食物。",
    "Plantation": "种植园",
    "Queue empty": "队列为空",
    "This building counts as a workstation": "这座建筑算作一个工作站",
    "Total buildings constructed": "已建成建筑物总数",
    "Total housing constructed (first 25 per building)": "已建成住房总数（每栋建筑前 25 栋）",
    "Village: Maximum housing": "村庄：最大住房数量",
    "Workers:": "工人：",
    "Fruit trees. Also produce food.": "果树。 还生产粮食。",
    "Do not neglect features. All important.": "不要忽视功能。 都很重要。",
    "Creatures look weird. Brown and hairy.": "居民看起来很奇怪。 棕色且多毛。",
    "Take an exam, where you have 1m 15s to get the highest possible score. You will receive golden dust as reward (150 - 199, based on your performance and chosen grade). If you achieve a score of 12, the exam is rated as perfect and you unlock the next grade.": "参加考试，您有 1 分 15 秒的时间来获得尽可能高的分数。 您将收到金尘作为奖励（150 - 199，根据您的表现和所选等级）。 如果您获得 12 分，则考试被评为完美，您可以解锁下一个等级。",
    " Study a bit first!": "先学一点吧！",
    "Ancient hourglass": "古老的沙漏",
    "Be patient. Think about purchases. Gems take long to get.": "要有耐心。 考虑购买。 宝石需要很长时间才能获得。",
    "Book": "书本",
    "Cancel": "取消",
    "Convert": "转换",
    "Convert exam passes to golden dust": "将考试合格证转化为金尘",
    "Each unlocked subject gives 10 books per hour, no matter the grade.": "每个解锁科目每小时提供 10 本书，无论年级如何。",
    "Exam pass": "考试通过",
    "Get new books. Every hour. Even more with better grades.": "获取新书。 每隔一小时。 成绩更好的话甚至更多。",
    "Get the highest possible score in 40s, and get a chance to improve your grade if you study on your best grade. Depending on your score, you gain (or lose) progress to the next grade. An average score of 6 is expected.": "在40秒内获得尽可能高的分数，如果你以最好的成绩学习，就有机会提高你的成绩。 根据您的分数，您会获得（或失去）升入下一年级的进度。 预计平均分为 6 分。",
    "Golden dust": "金尘",
    "Grades": "成绩",
    "Grades determine the difficulty of this subject. You can switch between grades at any time and unlock better grades by studying enough or getting a perfect exam score.": "成绩决定了该科目的难度。 您可以随时切换成绩，通过足够的学习或获得完美的考试成绩来解锁更好的成绩。",
    "It's hard to carry these heavy books": "搬运这些重书很困难",
    "Learn in school. Answer correctly. Get good grades.": "在学校学习。 正确回答。 取得好成绩。",
    "Math": "数学",
    "Practice": "实践",
    "Practice this subject without time pressure, but gain no rewards or grades": "在没有时间压力的情况下练习该科目，但不会获得任何奖励或成绩",
    "Requires ": "需要",
    "School": "学校",
    "Skip": "跳过",
    "Skip time for this feature": "跳过此功能的时间",
    "Solve equations": "求解方程式",
    "Still learning": "还在学习中",
    "Strange, we didn't need them at our old school. Here they are needed to take an exam": "奇怪的是，我们原来的学校不需要它们。 这里需要他们参加考试",
    "Study": "学习",
    "Take exam": "参加考试",
    "Time (in minutes)": "时间（分钟）",
    "You are new to this school, reducing your golden dust reward to 25%. Reach a higher global level to reduce this penalty, and remove it entirely by reaching global level 175.": "你是这所学校的新手，你的金尘奖励减少到25%。 达到更高的全局等级可以减少此惩罚，并通过达到全局等级 175 来完全消除它。",
    "You cannot lose grade progress at F grade.": "您不能失去 F 级的成绩进度。",
    "You cannot take exams at F grade.": "您不能参加 F 级考试。",
    "Food": "食物",
    "Fruit": "水果",
    "Fruit gain:": "果实增益：",
    "Grain": "粮食",
    "Grain from plants grown in the village. You think this should be processed before eating it, but the villagers don't care": "村里种植的植物的谷物。 你认为这个应该加工一下再吃，但村民不在乎",
    "Harvester": "收割机",
    "Sweet and juicy fruit, the villagers love these": "果实香甜多汁，深受村民喜爱",
    "Book gain:": "书本增益：",
    "Student": "学生",
    "Achievement hint": "成就提示",
    "Bottom": "底部",
    "Bottom left": "左下",
    "Common": "常见",
    "Dark mine is scary. But give metal.": "黑暗的我是可怕的。 但是给金属。",
    "Gem purchases": "宝石购买",
    "Icon only": "仅图标",
    "Increased": "增加",
    "Off": "关闭",
    "Particle amount": "粒子量",
    "Rare": "稀有",
    "Reduced": "降低",
    "Simple": "简单",
    "Text only": "仅文本",
    "Top": "顶部",
    "Top left": "左上",
    "Top right": "右上",
    "Metal": "金属",
    "Metal gain:": "金属增益：",
    "Miner": "矿工",
    "Your creatures found this metal by digging underground. Seems like the ground beneath this village isn't full of scrap": "你的居民通过挖掘地下发现了这种金属。 看来这个村庄的地下并没有充满废料",
    "Buy crafting station. Make better pickaxes.": "购买制作站。 制作更好的镐。",
    "Crafting station": "制作站",
    "Global level. Need to unlock new features. Progress in features to increase.": "全局水平。 需要解锁新功能。 进步功能增加。",
    "The crafting station allows you to consume ores to raise your pickaxe power and is essential to increase your damage": "制作站可以让你消耗矿石来提高你的镐的恁俩，这对于增加你的伤害至关重要",
    "Unlock: Pickaxe crafting": "解锁：制作镐子",
    "Click on ores to add them to crafting slots": "单击矿石将其添加到制作槽中",
    "Craft": "制作",
    "Craft pickaxe": "制作稿子",
    "Crafting power:": "制作能量：",
    "Forge": "锻造",
    "Get the best pickaxe possible for this craft": "为这门手艺找到最好的镐",
    "Golden hammer": "金锤",
    "Purity": "纯度",
    "To reach 50% minimum quality, your purity needs to match your impurity.": "为了达到 50% 的最低质量，您的纯度需要与您的杂质相匹配。",
    "Creatures are community now. Dance and celebrate.": "居民现在是共同体。 跳舞庆祝。",
    "Keep crafting. Sometimes good. Sometimes bad.": "继续制作。 有时很好。 有时不好。",
    "Metal capacity:": "金属容量：",
    "More metal": "更多金属",
    "Upgrades one of your crafting slots to premium, which halves impurity and doubles purity": "将您的一个制作槽升级为高级，从而使杂质减半并使纯度加倍",
    "Answer various equations to raise your score. Gain 1 score for each correct answer, and lose 1 score for each wrong answer (cannot go below 0). As your grade increases, numbers get bigger and new operators are introduced.": "回答各种方程式来提高你的分数。 每个正确答案得 1 分，每个错误答案扣 1 分（不能低于 0）。 随着等级的提高，数量会越来越多，并且会引入新的操作员。",
    "Crane": "起重机",
    "Garden": "花园",
    "Gold coin capacity:": "金币容量：",
    "Highest metal amount": "最高金属量",
    "Rust and metal": "铁锈和金属",
    "Safe": "保险箱",
    "Skyscraper": "摩天大楼",
    "Small house": "小屋",
    "Storage": "存储",
    "Tax rate causes your working villagers to consume food and pay taxes in return": "税率导致您的劳动村民消费食物并缴纳税款作为回报",
    "Tax rate:": "税率：",
    "Town hall": "市政厅",
    "Treasury": "财政部",
    "Unlock: Gold coin upgrades": "解锁：金币升级",
    "Well": "水井",
    "Well worker:": "水井工人:",
    "You are new to this school, reducing your golden dust reward to 30%. Reach a higher global level to reduce this penalty, and remove it entirely by reaching global level 175.": "你是这所学校的新手，你的金尘奖励减少到30%。 达到更高的全局等级可以减少此惩罚，并通过达到全局等级 175 来完全消除它。",
    "Answer": "回答",
    "Leave": "离开",
    "Aluminium hardening": "铝淬火",
    "Aluminium hardening maximum level:": "铝淬火最大等级：",
    "This is the power of your pickaxe and your base damage. Increase it by crafting a better pickaxe.": "这是你的镐的能量和你的基础伤害。 通过制作更好的镐来增加它。",
    "Know-it-all": "无所不知",
    "Lesson complete!": "课程完成！",
    "The lesson begins!": "课程开始了！",
    "Your grade improved!": "你的成绩提高了！",
    "Ore slots": "矿石插槽",
    "Crafting slots:": "制作插槽：",
    "Compressor": "压缩机",
    "Unlock: Aluminium compression": "解锁：铝压缩",
    "The compressor allows you to increase the ore amount per slot for higher purity": "压缩机允许您增加每个插槽的矿石量以获得更高的纯度",
    "More slots. Better pickaxes. Compress ore. Need more ore. Less bad pickaxes.": "更多插槽。 更好的镐。 压缩矿石。 需要更多或。 坏镐少一些。",
    "Friendly bat": "友好的蝙蝠",
    "Get relics. Helpful forever.": "获取遗物。 永远有帮助。",
    "Relics": "遗物",
    "Be an eager student. Receive golden dust. Can skip time.": "做一个热心的学生。 获得金尘。 可以跳过时间。",
    "Exam complete!": "考试结束！",
    "The exam begins!": "考试开始了！",
    "Best school grade": "最好的学校成绩",
    "This achievement is secret and does not give any bonuses.": "该成就是秘密的，不提供任何奖励。",
    "Buy an exam pass for": "购买考试通行证",
    "Crafting power": "制作能量",
    "Apply": "应用",
    "Blue": "蓝色",
    "Brown": "棕色",
    "Factory": "工厂",
    "Forest": "森林",
    "Cherry": "樱桃色",
    "Custom background": "自定义背景",
    "Cyan": "青色",
    "Green": "绿色",
    "Grey": "灰色",
    "Orange": "橙子",
    "Pink": "粉色",
    "Polar": "极地",
    "Prismatic": "棱柱形",
    "Purple": "紫色",
    "Red": "红色",
    "Sepia": "棕褐色",
    "Sky": "天空",
    "Yellow": "黄色",
    "Coins earned by selling food to your villagers": "通过向村民出售食物赚取金币",
    "Gold coin": "金币",
    "Metal bag": "金属包",
    "per food item consumed.": "每个消耗的食物项目。",
    "Resource bag": "资源包",
    "Tax rate": "税率",
    "Taxpayers": "纳税人",
    "Wallet": "钱包",
    "Working creatures pay taxes. Consume food. Give coin.": "劳动居民纳税。 消耗食物。 给硬币。",
    "Confirm": "确认",
    "Confirm action": "确认操作",
    "Storage very important. Often capacity the problem. Not price.": "存储非常重要。 往往是容量问题。 不是价格。",
    "You are about to buy the upgrade \"Student\", which costs rare currency. Are you sure you want to buy this?": "您即将购买升级版“学生”，需要花费稀有货币。 您确定要购买这个吗？",
    "Creatures eyeing on coins. Must keep coin safe. In safe.": "人们盯着硬币。 一定要保管好硬币。 在安全的地方。",
    "Capitalist": "资本家",
    "Coins gained": "获得的金币",
    "Creatures take water from hole. Use arms to grab bucket. With water.": "居民从洞里取水。 用手臂抓住水桶。 与水。",
    "Income is reduced to 50% due to overcap": "收入因上限减少至 50%",
    "Water capacity:": "水容量：",
    "Well worker": "水井工人",
    "Water gain:": "水增益：",
    "New ore. Use both for crafting. Best result.": "新矿石。 将两者用于手工制作。 最好的结果。",
    "Also learn to write. Get more books.": "还要学写字。 获取更多书籍。",
    "Literature": "文学",
    "Copper ore": "铜矿石",
    "New subject unlocked!": "新主题解锁！",
    "It emits a strange energy, as if it could change time itself": "它散发出一种奇怪的能量，仿佛可以改变时间本身",
    "Get the highest possible score in 40s, and get a chance to improve your grade if you study on your best grade. Depending on your score, you gain (or lose) progress to the next grade. An average score of 4 is expected.": "在40秒内获得尽可能高的分数，如果你以最好的成绩学习，就有机会提高你的成绩。 根据您的分数，您会获得（或失去）升入下一年级的进度。 预计平均分为 4 分。",
    "Write sentences": "写句子",
    "Another one of the missing ores. This one seems to yield better results than the previous one. How many more are down here?": "另一种失踪的矿石。 这一项似乎比前一项产生了更好的结果。 下面还有多少人？",
    "Aluminium anvil": "铝砧",
    "Aluminium tanks": "铝罐",
    "Copper cache": "铜存储",
    "Copper ore capacity:": "铜矿石容量：",
    "Just plain and simple water": "只是简单的水而已",
    "Water": "水",
    "Alloying": "合金化",
    "Workers": "工人",
    "Creature unfamiliar with house. And door. But likes it.": "对房子不熟悉的居民。 还有门。 但很喜欢。",
    "More copper": "更多铜",
    "Copper ore gain:": "铜矿石增益：",
    "More water": "更多水",
    "Highest water amount": "更高的水数量",
    "Aquaeduct": "渡槽",
    "Dig deeper. Find other ores.": "深入挖掘。 寻找其他矿石。",
    "Pretty flowers. Creatures seem to not care. But still pretty.": "漂亮的花。 居民似乎并不关心。 但还是很漂亮。",
    "Hullbreaker": "破壳者",
    "Unlock: Copper compression": "解锁：铜压缩",
    "Toughness:": "韧性：",
    "Reduce toughness. Advance further.": "降低韧性。 进一步前进。",
    "Attack": "攻击",
    "Attack +": "攻击+",
    "Attack:": "攻击：",
    "Bone": "骨头",
    "Bone gain": "骨头增益",
    "Health": "生命值",
    "Health +": "生命值+",
    "Health:": "生命值：",
    "Horde": "部落",
    "Hordes of monsters. Block path. Only one way to progress. Kill enough. Then kill leader.": "成群的怪物。 块路径。 只有一种方法可以进步。 杀够了。 然后杀掉首领。",
    "Player": "玩家",
    "Reach the boss": "到达Boss",
    "Reduce toughness. Advance further.": "降低韧性。 进一步前进。",
    "Regular attacks happen every second and have the following damage distribution:": "常规攻击每秒发生一次，伤害分布如下：",
    "Skeletal remains of the enemies you have slain": "你杀死的敌人的骸骨",
    "The amount of damage dealt per attack": "每次攻击造成的伤害量",
    "The amount of damage you can take before dying": "死亡前你能承受的伤害量",
    "Town of creatures. They dance again. Seems important to them.": "生物之城。 他们又跳舞了。 看来对他们来说很重要。",
    "Aquarium": "水族馆",
    "Church": "教会",
    "Faith gain:": "信仰增益：",
    "Glass capacity:": "玻璃容量：",
    "Glassblower:": "玻璃吹制工：",
    "Glassblowery": "玻璃吹制厂",
    "House": "房子",
    "Knowledge capacity:": "知识容量：",
    "Knowledge tower": "知识塔",
    "Librarian:": "图书管理员：",
    "Library": "图书馆",
    "Local government": "地方政府",
    "Miniature smith": "微型铁匠",
    "Sawmill": "锯木厂",
    "Shed": "工棚",
    "This gives you access to the prestige option of the village": "这使您可以享受村庄的声望选项",
    "Tunnel": "隧道",
    "Unlock: Basics upgrade": "解锁：基础升级",
    "Unlock: Hatchet upgrade": "解锁：斧头升级",
    "Unlock: Scythe upgrade": "解锁：镰刀升级",
    "Mighty": "强大",
    "Next upgrade unlocks at 3 Maximum zone": "下一次升级将解锁于第 3 个最大区域",
    "Slayer": "杀手",
    "Respawn time": "重生时间",
    "Fight boss": "打Boss",
    "Fighting": "战斗",
    "Flee from the boss": "逃离Boss",
    "Run away from this battle and keep fighting regular enemies": "逃离这场战斗并继续与普通敌人战斗",
    "You have defeated enough enemies to challenge the boss of this zone": "你已经击败了足够多的敌人来挑战这个区域的boss",
    "Scythe": "镰刀",
    "Horde: Highest zone boss defeated": "部落：击败最高区域首领",
    "One group dead. But more appear.": "一群死了。 但更多的出现。",
    "Zone cleared": "区域已清理",
    "Training": "训练",
    "How much time you need to recover from dying": "你需要多少时间才能从死亡中恢复过来",
    "Advance further. Carry more bones.": "进一步前进。 携带更多骨头。",
    "Dog's favourite": "狗的最爱",
    "Resilience": "恢复力",
    "Revive:": "恢复：",
    "Bones gained": "获得的骨头",
    "Dagger": "匕首",
    "Deal": "造成",
    "Equip": "装备",
    "Equip items. Improve stats. Use abilities in combat.": "装备物品。 改善属性数据。 在战斗中使用技能。",
    "Equipment capacity": "装备容量",
    "Explorer": "探险家",
    "health": "生命值",
    "Maximum zone": "最大区域",
    "Maximum zone in under 30 minutes": "30分钟内达到最大区域",
    "physical damage": "物理伤害",
    "Restore": "恢复",
    "Shirt": "衬衫",
    "Swift strikes": "快速出击",
    "Unequip": "脱下",
    "Anger": "愤怒",
    "Bone bag": "骨袋",
    "Bone capacity:": "骨容量：",
    "Bone gain:": "骨增益：",
    "Boss": "Boss",
    "Buy card packs. Collect cards. Get bonuses.": "购买卡包。 收集卡片。 获得奖金。",
    "Card pack": "卡包",
    "Card pack contents": "卡包内容",
    "Cards": "卡片",
    "Collect a duplicate of a card": "收集卡片的副本",
    "Creatures smart. Did not expect. Only say ugh.": "生物聪明。 没想到。 只能说呃。",
    "Crit chance:": "致命一击几率：",
    "Cup of milk": "一杯牛奶",
    "Division shield": "师盾",
    "Equipment capacity:": "设备容量：",
    "Fight in higher zones. Find better equipment. Also find chance higher.": "在更高的区域战斗。 寻找更好的设备。 发现几率也更高。",
    "Fight monsters. Find new items.": "与怪物战斗。 寻找新物品。",
    "Go to the prestige menu and equip the duplicate card (must be the same feature as seen at the bottom right of the card)": "进入声望菜单并装备重复卡（必须与卡右下角所示的功能相同）",
    "Guardian angel": "守护天使",
    "Into darkness": "进入黑暗",
    "Librarian": "图书管理员",
    "Meeting new people": "结识新朋友",
    "Miners and equipment": "矿工和装备",
    "More bones": "更多骨头",
    "More power": "更多动力",
    "Perform a prestige with the card equipped": "使用装备的卡执行声望",
    "Reach zone 10. After 100 enemies. Find new currency.": "到达 10 区。击败 100 名敌人后。 寻找新货币。",
    "Revive": "恢复",
    "Rookie on the battlefield": "战场上的菜鸟",
    "Scrap logistics": "废料物流",
    "Star shield": "星盾",
    "The card will get consumed and its effects are active until you prestige again": "该卡将被消耗，其效果将一直有效，直到您再次声望为止",
    "Unlock dweller. Prepare for new cycle. Needs time though.": "解锁居民。 为新的周期做好准备。 不过还需要时间。",
    "Unlock prestige for one of your main features": "解锁您的主要功能之一的声望",
    "You are about to buy the card pack \"Into darkness\", which costs rare currency. Are you sure you want to buy this?": "您将要购买“进入黑暗”卡包，该卡包需要花费稀有货币。 您确定要购买这个吗？",
    "You are about to buy the upgrade \"More damage\", which costs rare currency. Are you sure you want to buy this?": "您即将购买升级“更多伤害”，这需要花费稀有货币。 您确定要购买这个吗？",
    "You collected your first cards! Most cards have an effect when active, to enable it you have to do the following:": "您收集了第一张卡片！ 大多数卡片在激活时都会产生效果，要启用它，您必须执行以下操作：",
    "Copper tanks": "铜罐",
    "Depth Dweller": "深度居民",
    "Hatchet": "斧头",
    "Recovery:": "恢复：",
    "Rest": "休息",
    "This action requires consumables that you do not have. Do you want to buy these for rare currency?": "此操作需要您没有的消耗品。 您想用稀有货币购买这些吗？",
    "This gives access to the prestige option of the mine": "这可以让您获得矿山的声望选项",
    "Unlock: Depth dweller": "解锁：深度居民",
    "Unlock: Pickaxe upgrade": "解锁：镐升级",
    "Crafting slots": "制作槽",
    "Effects (when active):": "效果（激活时）：",
    "Full collection reward:": "集齐奖励：",
    "Mining card capacity": "矿卡容量",
    "Mining cards": "矿卡",
    "Scrap capacity": "废料容量",
    "Scrap gain": "废料收益",
    "This card can be found in the following packs:": "这张卡可以在以下包中找到：",
    "This card cannot be found in your currently available packs": "在您当前可用的包中找不到此卡",
    "A disgusting organ that can be found at zone 10 or higher after enemy #100": "一个恶心的器官，可以在敌人 #100 之后的 10 区或更高区域找到",
    "Aluminium expansion": "铝膨胀",
    "Boots": "脚部",
    "Dig too deep. Some ores disappear. Need specific depths. Then they come back.": "挖得太深了。 一些矿石消失了。 需要具体深度。 然后他们回来了。",
    "First strike": "先发制人",
    "Fish look pretty. Want to eat them. But can't. Not now.": "鱼看起来很漂亮。 想吃它们。 但不能。 现在不要。",
    "highest zone bones": "最高区骨头",
    "magical damage": "魔法伤害",
    "Mental resources": "精神资源",
    "Monster bag": "怪物包",
    "Monster part": "怪物部分",
    "Monster part capacity:": "怪物部分容量：",
    "Monsters look scary. Don't worry. Always respawn.": "怪物看起来很可怕。 不用担心。 总会重生。",
    "Ore gain:": "矿石增益：",
    "Pickaxe": "镐",
    "Refinery": "炼油厂",
    "Thick skin": "厚脸皮",
    "Unlock: Watering can upgrade": "解锁：喷壶升级",
    " at least": "最少",
    " at most": "最多",
    "Aluminium ore gained": "铝矿石增益",
    "Clover": "三叶草",
    "Combat training": "格斗训练",
    "Completion reward:": "完成奖励：",
    "Copper expansion": "铜扩张",
    "Creature got used to house. Opens window. Big smile.": "生物已经习惯了居住。 打开窗口。 灿烂的笑容。",
    "Crit chance": "致命一击几率",
    "Crit damage": "暴击伤害",
    "Crystal aluminium storage": "水晶铝储物",
    "Crystal basics": "水晶基础知识",
    "Crystal copper storage": "水晶铜收纳",
    "Crystal lens": "水晶镜片",
    "Crystal storage": "水晶储存",
    "Crystal tin storage": "水晶锡储存",
    "Crystal tips": "水晶提示",
    "Current / highest possible dweller depth": "当前/最大可能的居住深度",
    "Dangerous weapons": "危险武器",
    "Dangers in the dark": "黑暗中的危险",
    "Depth dweller": "深度居民",
    "Depth dweller speed:": "深度停留速度：",
    "Digging deeper": "深层发掘",
    "Do quests. Receive more notes. Get relic when done.": "做任务。 接收更多笔记。 完成后获得遗物。",
    "Drill fuel": "钻机燃料",
    "Drills and depths": "钻孔和深度",
    "Duplicate cards can be equipped, and will be consumed on next prestige to activate their effects. These effects stay active until you prestige again.": "可以装备重复的卡牌，并将在下一个声望时消耗卡牌以激活其效果。 这些效果会一直保持有效，直到您再次获得声望为止。",
    "Equipment chance": "装备几率",
    "For each completed half meter of current dweller depth, your prestige reward increases.": "当前居民深度每完成半米，你的声望奖励就会增加。",
    "Frozen forever": "永远冰冻",
    "Generals": "将军",
    "Green crystal": "绿水晶",
    "Green crystal gain:": "绿水晶增益：",
    "Grobodal": "格罗博达尔",
    "Highest possible dweller depth is 10% of your maximum depth in the mine.": "居民的最高可能深度是矿井中最大深度的 10%。",
    "Horde card capacity": "部落卡容量",
    "Knowledge gain:": "知识获取：",
    "Longsword": "长剑",
    "Lurking snake": "潜伏的蛇",
    "Maintaining safety": "维护安全",
    "Maximum dweller depth": "最大居住深度",
    "Megabomb": "巨型炸弹",
    "Metal bag maximum level:": "金属袋最大等级：",
    "Monster part gain:": "怪物部分增益：",
    "More green crystals": "更多绿色水晶",
    "More knowledge": "更多知识",
    "More monster parts": "更多怪物零件",
    "New ore. Another one. New ores better. But impure.": "新矿石。 另一个。 新矿石更好。 但不纯。",
    "No cards found": "没有找到卡片",
    "Prestige": "声望",
    "Reset this feature in exchange for prestige currency": "重置此功能以换取声望货币",
    "Resource bag maximum level:": "资源包最高等级：",
    "Surveillance camera": "监控摄像头",
    "The dweller starts fast and gets slower the closer it gets to its limit.": "居民开始时速度很快，越接近极限，速度就越慢。",
    "This is a premium crafting slot. Impurity is halved and purity is doubled.": "这是一个高级制作槽。 杂质减半，纯度加倍。",
    "Time spent": "所花费的时间",
    "Time spent this prestige cycle": "此声望周期花费的时间",
    "Tin ore capacity:": "锡矿石产能：",
    "Unlock: Investment upgrade": "解锁：投资升级",
    "Village card capacity": "乡村卡片容量",
    "Wallet maximum level:": "钱包最高等级：",
    "Watering can": "喷壶",
    "You are about to buy the card pack \"Rookie on the battlefield\", which costs rare currency. Are you sure you want to buy this?": "您即将购买“战场菜鸟”卡包，该卡包需要花费稀有货币。 您确定要购买这个吗？",
    "You are about to buy the upgrade \"More scrap\", which costs rare currency. Are you sure you want to buy this?": "您即将购买升级版“更多废品”，这需要花费稀有货币。 您确定要购买这个吗？",
    "You are about to buy the upgrade \"Premium crafting slots\", which costs rare currency. Are you sure you want to buy this?": "您即将购买升级版“高级制作槽”，这需要花费稀有货币。 您确定要购买这个吗？",
    "Drilling straight down": "垂直向下钻",
    "Highest knowledge amount": "最高知识量",
    "Mastermind": "策划者",
    "Monster parts gained": "获得怪物零件",
    "Next upgrade unlocks at 5 Maximum dweller depth": "下一次升级将在 5 最大居民深度解锁",
    "Nothing is wasted": "没有任何东西被浪费",
    "Horde cards": "部落卡片",
    "These crystals look amazing! You would have never found them without your depth dweller": "这些水晶看起来棒极了！ 如果没有你的深度居民，你永远不会找到它们",
    "You are about to prestige, resetting all of your progress in this feature in exchange for prestige currency. Are you sure you want to prestige?": "您即将获得声望，重置您在此功能中的所有进度，以换取声望货币。 你确定你想要声望吗？",
    "Mud brick": "泥砖",
    "Relic gained:": "遗物增益：",
    "Smelt sand. Can be shaped. Dangerous work.": "闻沙子的味道。 可以定型。 危险的工作。",
    "Autofight horde boss": "自动战斗部落Boss",
    "Card pack content": "卡包内容",
    "A light material is a welcome change to the darkness at these depths. The hole to the surface is getting hard to see": "轻质材料对于这些深处的黑暗来说是一种受欢迎的改变。 表面的洞越来越难以看见",
    "Aluminium ore capacity": "铝矿石产能",
    "Basic equipment": "基础设备",
    "Break same rock 1000 times. At 50m or deeper. Find something new.": "敲碎同一块岩石 1000 次。 50m或更深处。 寻找新的东西。",
    "Cave locations": "洞穴地点",
    "Copper heap": "铜堆",
    "Copper ore capacity": "铜矿石产能",
    "Depth dweller speed": "深度停留速度",
    "Detonate rock pile": "引爆石堆",
    "Disease analysis": "病情分析",
    "Dripstone cave": "滴水石洞",
    "Extraction": "萃取",
    "Glass capacity": "玻璃容量",
    "Glass gain": "玻璃增益",
    "Glassblower": "玻璃吹制工",
    "Green crystal gain": "绿晶增益",
    "Hammer": "锤子",
    "Helmet shelf": "头盔架",
    "Hydraulic press": "液压机",
    "Industrial revolution": "工业革命",
    "Into the depths": "进入深处",
    "Investment": "投资",
    "Keep: Hut": "保留：小屋",
    "Knowledge": "知识",
    "Light the fuse!": "点燃保险丝！",
    "Neighborhood": "邻里",
    "Observe and learn": "观察和学习",
    "Ore gain": "矿石增益",
    "Ore quality": "矿石品质",
    "Pick or shovel?": "镐还是铲子？",
    "Rock bottom": "最低点",
    "Rocket launcher": "火箭发射器",
    "Stone gain": "石增益",
    "Surface rock": "地表岩石",
    "Tin ore": "锡矿",
    "Tin ore capacity": "锡矿石产能",
    "To the surface": "到表面",
    "Too small": "太小",
    "Water capacity": "水容量",
    "Water gain": "增水量",
    "Wood gain": "木材增益",
    "You are about to buy the card pack \"Drills and depths\", which costs rare currency. Are you sure you want to buy this?": "您即将购买卡包“钻探与深度”，该卡包需要花费稀有货币。 您确定要购买这个吗？",
    "You are about to buy the card pack \"Into darkness\" x3, which costs rare currency. Are you sure you want to buy this?": "您将要购买卡包“进入黑暗”x3，该卡包需要稀有货币。 您确定要购买这个吗？",
    "You are about to buy the card pack \"Meeting new people\", which costs rare currency. Are you sure you want to buy this?": "您即将购买“结识新朋友”卡包，该卡包需要花费稀有货币。 您确定要购买这个吗？",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Save (": "保存 (",
    "Premium crafting slots": "高级制作槽",
    "Book: ": "书籍: ",
    "Score: ": "分数: ",
    "Enemy #": "敌人 #",
    "Into darkness ": "走进黑暗 ",
    "Rookie on the battlefield ": "战场上的菜鸟 ",
    "Drills and depths ": "钻孔和深度",
    "MI-": "MI-",
    "HO-": "HO-",
    "VI-": "VI-",
    "Meeting new people ": "结识新朋友 ",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "/s": "/秒",
    "Impurity": "杂质",
    "(PERFECT!)": " (完美!)",
    " (School)": "（学校）",
    " items equipped": "装备的物品",
    "(NEW!)": "(新!)",
    "Pickaxe crate": "镐箱",
    "Working hard": "努力工作",
    "Temporary storage": "临时存储",
    "Filled crate": "装满的箱子",
    "Quality control": "质量控制",
    " Megabomb": " 超级炸弹",
    " cards equipped": " 装备的卡片",
    " Lurking snake": " 潜伏的蛇",
    " Frozen forever": "  永远冰冻",
    " Surveillance camera": "  监控摄像头",
    " Into the depths": "走进深处",
    " Hydraulic press": "液压机",
    " Pick or shovel?": "镐还是铲子？",
    " Rocket launcher": " 火箭发射器",
    " Basic equipment": " 基础装备",
    " Light the fuse!": " 点燃保险丝！",
    " Into the depths": " 进入深处",
    " Helmet shelf": " 头盔架",
    " Too small": " 太小了",
    " To the surface": " 到表面",
    " Extraction": " 萃取",
    " Hydraulic press": " 液压机",
    " Detonate rock pile": " 引爆石堆",
    " Surface rock": " 地表岩石",
    " Dripstone cave": " 滴水石洞",
    " Outside camping": " 户外露营",
    " Playground": " 操场",
    " Camping trip": " 野营之旅",
    " Disease analysis": " 病情分析",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^([\d\.]+)s\)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^ \(([\d\.]+)m ([\d\.]+)s\)$/,
    /^: ([\d\.]+)m ([\d\.]+)s$/,
    /^ \(([\d\.]+)h ([\d\.]+)m\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^x([\d\.]+) $/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.]+)K$/,
    /^([\d\.]+)K \/ ([\d\.]+)K$/,
    /^([\d\.]+)K \~ ([\d\.]+)K$/,
    /^([\d\.]+)K \/ ([\d\.]+)$/,
    /^([\d\.]+)M \/ ([\d\.]+)M$/,
    /^([\d\.]+)M \/ ([\d\.]+)T$/,
    /^([\d\.]+)T \/ ([\d\.]+)T$/,
    /^([\d\.]+)T \/ ([\d\.]+)Qa$/,
    /^([\d\.]+)B \/ ([\d\.]+)T$/,
    /^([\d\.]+)B \/ ([\d\.]+)M$/,
    /^([\d\.]+)B \/ ([\d\.]+)K$/,
    /^([\d\.]+)B \/ ([\d\.]+)$/,
    /^([\d\.]+)M \/ ([\d\.]+)K$/,
    /^([\d\.]+)M \/ ([\d\.]+)$/,
    /^([\d\.]+)M \/ ([\d\.]+)B$/,
    /^([\d\.]+)B \/ ([\d\.]+)B$/,
    /^([\d\.]+)K \/ ([\d\.]+)M$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^This rock was broken (.+) time$/, '距离这块岩石被击破还需要 $1 次'],
    [/^This rock was broken (.+) times$/, '距离这块岩石被击破还需要 $1 次'],
    [/^Gain (.+) on hit, (.+) on break, (.+) per second$/, '击中时获得 $1，击碎时获得 $2 ，每秒 $3'],
    [/^Next upgrade unlocks at (.+) Maximum depth$/, '下一次升级将在最大深度 $1 处解锁'],
    [/^Gain new gems every time the bar fills. Each achievement increases generation speed by (.+). Your (.+) achievements increase generation speed by (.+), from (.+) to (.+).$/, '每次进度条填满时都会获得新的宝石。 每项成就都会使生成速度提高 $1。 你的 $2 成就将生成速度提高 $3，从 $4 到 $5。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^You reach (.+) in (.+)$/, '你在 $2 达到了 $1'],
    [/^Next upgrade unlocks at (.+) Maximum zone$/, '下一次升级将在第 $1 个最大区域解锁'],
    [/^Each enemy in the same zone has (.+) attack, (.+) health and (.+) bones compared to the previous enemy. This is enemy (.+) and has (.+) attack, (.+) health and (.+) bones. All of these effects reset when you die.$/, '与前一个敌人相比，同一区域中的每个敌人都有 $1 攻击力、$2 生命值和 $3 骨骼。 这是敌人 $4，攻击力 $5，生命值 $6，骨骼 $7。 当你死后，所有这些效果都会重置。'],
    [/^To challenge the boss of this zone, you need to defeat (.+) enemies without dying$/, '要挑战这个区域的Boss，你需要在不死的情况下击败 $1 个敌人'],
    [/^Can be found at (.+)m or below$/, '可以在 $1米 以下找到'],
    [/^All working citizens consume up to (.+) of each food per second and pay taxes equal to (.+)$/, '所有工作公民每秒消耗每种食物 $1，缴纳相当于 $2 的税'],
    [/^Unlock: Tier (.+) buildings$/, '解锁：$1 级建筑'],
    [/^You are new to this school, reducing your golden dust reward to (.+). Reach a higher global level to reduce this penalty, and remove it entirely by reaching global level (.+).$/, '你是这所学校的新手，你的金尘奖励减少到 $1。 达到更高的全局等级可以减少此惩罚，并通过达到全局等级 $2 来完全消除它。'],
    [/^Take an exam, where you have (.+) to get the highest possible score. You will receive golden dust as reward \((.+), based on your performance and chosen grade\). If you achieve a score of (.+), the exam is rated as perfect and you unlock the next grade.$/, '参加考试，您有 $1 的时间来获得尽可能高的分数。 您将获得金尘作为奖励（$2，根据您的表现和所选等级）。 如果您获得 $3 分，则考试被评为完美，您可以解锁下一个等级。'],
    [/^Income is reduced to (.+) due to overcap (.+)$/, '由于达到上限，收入减少至 $1 $2'],
    [/^Consume selected ores and create a new pickaxe with a random power value. If it is better than your current pickaxe \((.+) power\), replace it.$/, '消耗选定的矿石并创建具有随机能量值的新镐。 如果它比您当前的镐（$1 能量）更好，请更换它。'],
    [/^You get a new exam pass every day \(next one in (.+)\) and every (.+) global levels.$/, '您每天都会获得一张新的考试通行证（下一张在 $1 内），并且每 $2 个全局等级都会获得一张新的考试通行证。'],
    [/^Consuming up to (.+) per second$/, '每秒最多消耗 $1'],
    [/^Note (.+) found$/, '发现笔记 $1'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) Power$/, '$1 能量'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+)m$/, '$1米'],
    [/^Zone ([\d\.,]+)$/, '区域 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^(.+)\% physical$/, '$1\% 物理'],
    [/^(.+)\% grade$/, '$1\% 年级'],
    [/^\+(.+) Purity$/, '\+$1 纯度'],
    [/^\+(.+) Golden dust$/, '\+$1 金尘'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);